version: "3"

services:
  object-storage:
    image: minio/minio:RELEASE.2024-08-29T01-40-52Z.fips
    container_name: object-storage
    ports:
      - "9010:9000"
      - "9011:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server --console-address ":9001" /data
    volumes:
      - minio-object-storage:/data

volumes:
  minio-object-storage:
